### ISSUE TITLE
Fuel "leak"

### ISSUE THREAD

**Issue by Inkognito665** [D1ngtalk/Yourcontrols-config-for-Fenixsim-A320#10]
Hello everyone!
First of all, I'd like to say that this config is really good and very useful for shared cockpit flights! We appreciate that! 

We found a new important issue. During flight one of us sometimes experiences deifferent engine thrust settings (I know that this issue is reported already), but because of dif. engine thrust settings we have different FF => FOB is different, moreover, sometimes fuel in the tanks are different. I mean that we have same FOB, but in different tanks and aircraft alerts that there is a fuel leak.

The only way to prevent this from happening: one of you (PM) disconnects his AT and set thrust manually, so PM's thrust settings equals PF's.
P.S. this fix also fixes flight control's issue 

![изображение](https://user-images.githubusercontent.com/125677421/219696892-e79e5baa-ccd3-40ad-9f78-3600c3c5f26d.png)
![изображение](https://user-images.githubusercontent.com/125677421/219697005-fa4dd2ec-1c1e-46fb-a7d3-ff8d30429e92.png)

**Comment by crisk73** [comment]
How does only PM disconnect AT? By prior disconnecting YC and then reconnecting again so as to de-sync the AT?

**Comment by Inkognito665** [comment]
> 

That's a good question. For some reasnons during our 2nd leg we found out that once PM set his levers to IDLE PF's ATHR does not disconnect.

p.s. we also found out that if PM set his throttle to idle FOB will be the same

**Comment by D1ngtalk** [comment]
Last week, microsoft's server had some problem, effect live weather service. if both side's weather is not same, it will make one of you two have more throttle to make fuel lost. Now the live weather service seems fixed, so it fine.
