### ISSUE TITLE
Plans on updating it for Fenix V2?

### ISSUE THREAD

**Issue by LolloB738** [D1ngtalk/Yourcontrols-config-for-Fenixsim-A320#17]
Are there any plans on updating the file for compatibility with the new Fenix V2 once Block2 gets released?

**Comment by D1ngtalk** [comment]
Yes. But we also have plan to rewrite a new share cockpit software for MSFS, it will more fitable with Fenix.

**Comment by LolloB738** [comment]
> Yes. But we also have plan to rewrite a new share cockpit software for MSFS, it will more fitable with Fenix.

That's some good news! Thanks!

**Comment by Fuschl-dev** [comment]
Will there be a V2 Config before the new software and can you publish a roadmap or tell us how far the development is?
