### ISSUE TITLE
Flight Control Issue.

### ISSUE THREAD

**Issue by AUAA320** [D1ngtalk/Yourcontrols-config-for-Fenixsim-A320#4]
Hi there,

Firstly, thanks for this great add-on! I was waiting for that since quite some time, and finally, someone created a working Configuration!

During my initial flight-tests with different colleagues, we discovered an issue which seem to be occurring very frequently:

1. Flight Controls: During the Flight-Control-Check on Ground, we always notice that all the controls are twisted. For example, if I pull the Side-Stick, for me, the ECAM F-CTL Page indicates that the Elevators are in the full up position, however, for the Second Person connected, the elevators are indicated in the full down position.

Thanks a lot!

**Comment by D1ngtalk** [comment]
Fix in lastest

**Comment by AUAA320** [comment]
Fixed - thanks a lot!

**Comment by D1ngtalk** [comment]
Thanks for your comment, I will mark this problem as close
