### ISSUE TITLE
Hot Brake Issue

### ISSUE THREAD

**Issue by AUAA320** [D1ngtalk/Yourcontrols-config-for-Fenixsim-A320#5]
Hi there,

There seems to be another issue:
After departing, and after landing, the Slave Connection to your controls often gets Hot-Brake Warnings. I am aware, that this is common also with other Your-Controls Aircraft, however, is there perhaps any way to fix it?

Deleting the Failure in the Maintenance Menu helps!

Regards.

**Comment by D1ngtalk** [comment]
I try to fix it in the lastest release, but I have not verify yet.

**Comment by D1ngtalk** [comment]
if this problem get better in lastest release, you can comment it here :>

**Comment by AUAA320** [comment]
It seems to have worked - thanks a lot!

**Comment by D1ngtalk** [comment]
Thanks for your comment, I will mark this problem as close
